# Generated by Django 4.0.6 on 2022-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOs',
            },
        ),
    ]
